apiVersion: v1
kind: Service
metadata:
  name: student-score-prediction-model-service
spec:
  type: LoadBalancer
  selector:
    app: student-score-prediction-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501